
name: Horusec Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  horusec:
    permissions:
      contents: read 
      security-events: write 
      actions: read 

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Horusec Scan
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with: # optional arguments
          arguments: >-
            -p ./
            -o json
            -O ./horusec-report.json
            --information-severity=true
      - name: Horusec Output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: horusec-security-report
          path: ./horusec-report.json
          retention-days: 7
          
