
name: Horusec Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '33 7 * * 6'

jobs:
  horusec:
    permissions:
      contents: read 
      security-events: write 
      actions: read 

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Horusec Scan
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with: # optional arguments
          arguments: -p ./
          
